const CombatUnitStatus = {
  REGISTRED: 'registered',
  LAUNCHED: 'launched',
  LOST: 'lost_connection',
  STOPPED: 'stopped',
  ATTACK_TARGET: 'attacking',
};

const points = [
  {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Point',
      coordinates: [45.179471969604485, 42.6486067022724],
    },
  },
  {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Point',
      coordinates: [45.184879302978516, 42.650184942521335],
    },
  },
  {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Point',
      coordinates: [45.18110275268555, 42.653025674055456],
    },
  },
];

const testUnits = {
  // 4: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-1',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   detection_radius: 1000,
  //   uav_type: '3',
  //   uav_role: '3',
  // },
  // 5: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-2',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 6: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-3',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 7: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-4',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 8: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-5',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 9: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-6',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 10: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-7',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 11: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-8',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 12: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-9',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 13: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-10',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 14: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-11',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 15: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-12',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 16: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-13',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 17: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-14',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 18: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-15',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 19: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-16',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 20: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-17',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 21: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-18',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 22: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-19',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  // 23: {
  //   status: CombatUnitStatus.LAUNCHED,
  //   tail_number: 'RAL-20',
  //   fuel_resource: 0.85,
  //   time_for_prepare: 30,
  //   uav_type: '4',
  //   uav_role: '4',
  // },
  4: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-1',
    fuel_resource: 16,
    time_for_prepare: 30,
    detection_radius: 1000,
    uav_type: '1',
    uav_role: '1',
  },
  5: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-2',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
    attack_coords: [
      { x: 42.61627553413439, y: 45.155181884765625 },
      { x: 42.603136199729526, y: 45.15758514404297 },
    ],
  },
  6: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-3',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
    attack_coords: [{ x: 42.603136199729526, y: 45.188140869140625 }],
  },
  7: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-4',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  8: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-5',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  9: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-6',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  10: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-7',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  11: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-8',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  12: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-9',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  13: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-10',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  14: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-11',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  15: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-12',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  16: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-13',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  17: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-14',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  18: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-15',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  19: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-16',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  20: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-17',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  21: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-18',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  22: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-19',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
  23: {
    status: CombatUnitStatus.LAUNCHED,
    tail_number: 'ORLAN-20',
    fuel_resource: 16,
    time_for_prepare: 30,
    uav_type: '2',
    uav_role: '2',
  },
};

const testUnitParams = {
  4: {
    globalPosition: {
      lattitude: 42.6486067022724,
      longtitude: 45.179471969604485,
      altitude: 1200.0,
    },
  },
  5: {
    globalPosition: {
      lattitude: 42.650184942521335,
      longtitude: 45.184879302978516,
      altitude: 400.0,
    },
  },
  6: {
    globalPosition: {
      lattitude: 42.653025674055456,
      longtitude: 45.18110275268555,
      altitude: 400.0,
    },
  },
};

const testUnitTypes = {
  1: {
    name: 'Orlan10Scout',
  },
  2: {
    name: 'Orlan10Striker',
  },
  3: {
    name: 'RALX6Scout',
  },
  4: {
    name: 'RALX6Striker',
  },
};

const testUnitRoles = {
  1: {
    name: 'Разведчик',
    uav_type: '1',
  },
  2: {
    name: 'Ударный',
    uav_type: '2',
  },
  3: {
    name: 'Разведчик',
    uav_type: '3',
  },
  4: {
    name: 'Ударный',
    uav_type: '4',
  },
};

module.exports = {
  testUnits,
  testUnitParams,
  testUnitTypes,
  testUnitRoles,
};
